active_profile: api_qwen3_coder
profiles:
  local_haiku:
    name: local_haiku
    driver: cli:claude
    model: haiku
    validator_model: haiku
    tracker: noop
  local_sonnet:
    name: local_sonnet
    driver: cli:claude
    model: anthropic:sonnet
    validator_model: anthropic:haiku
    tracker: noop
  local_opus:
    name: local_opus
    driver: cli:claude
    model: opus
    validator_model: anthropic:haiku
    tracker: noop
  api_minimax_m2:
    name: api_minimax_m2
    driver: api:openrouter
    model: minimax/minimax-m2
    validator_model: anthropic:haiku
    tracker: noop
  api_qwen3_coder:
    name: api_qwen3_coder
    driver: api:openrouter
    model: qwen/qwen3-coder
    validator_model: anthropic:haiku
    tracker: noop